# Site settings
title: Kenneth Chung
description: Kenneth Chung's website
url: "kenneth2chung.github.io" # the base hostname & protocol for your site
github_username: kenneth2chung
markdown: kramdown
theme: jekyll-theme-minimal